#include "RepositoryManager.h"

MapRepository RepositoryManager::s_MapRepository;
SpriteRepository RepositoryManager::s_SpriteRepository;
TokenItemRepository RepositoryManager::s_TokenItemRepository;
BackgroundLayerRepository RepositoryManager::s_BgLayerRepository;
MapLayerRepository RepositoryManager::s_MapLayerRepository;
FoWLayerRepository RepositoryManager::s_FoWLayerRepository;
DrawingLayerRepository RepositoryManager::s_DrawingLayerRepository;
GameObjectRepository RepositoryManager::s_GameObjectRepository;
CharacterRepository RepositoryManager::s_CharacterRepository;
